CREATE TABLE post (
    id INT UNSIGNED AUTO_INCREMENT, 
    created_by INT UNSIGNED NOT NULL, 
    image VARCHAR(255), 
    text TEXT, 
    created_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    likes INT UNSIGNED, 
    PRIMARY KEY (id)
);

CREATE TABLE images (
    id INT UNSIGNED AUTO_INCREMENT, 
    post_id INT UNSIGNED NOT NULL, 
    url VARCHAR(255) NOT NULL, 
    PRIMARY KEY(id)
);

CREATE TABLE user (
    id INT UNSIGNED AUTO_INCREMENT,
    img_avatar VARCHAR(255),
    text TEXT,
    name VARCHAR(100) NOT NULL  
);
